Integrar Multer
Ditmar/api-openscience pull request #22
Opened 2024-11-23 02:11 UTC by LuisPerez007

.....

2024-11-24 16:12 UTC, Ditmar requested changes
please add the evidences of your test using postman

2024-11-24 16:12 UTC, Ditmar commented on src/controller/routes/images-routes.ts
> +        //uploader.single('image'), // Middleware para manejar la imagen
remove this comment

2024-11-24 16:12 UTC, Ditmar commented on src/controller/routes/images-routes.ts
> +                return res.status(400).json({ error: 'No se subió ninguna imagen.' });
don't hard-coded the code status

2024-11-24 16:12 UTC, Ditmar commented on src/controller/routes/volume-routes.ts
> +                imageMessage: 'Imagen cargada exitosamente.',
use ingles for the messages

2024-11-27 18:30 UTC, LuisPerez007 commented
PRUEBAS
![image](https://github.com/user-attachments/assets/9a3d6a8b-7287-4a56-af25-1a7b76e25c70)
![image](https://github.com/user-attachments/assets/f31741a6-1843-42cc-89a1-63faf5ff5db0)
![image](https://github.com/user-attachments/assets/aee87bde-6f58-47a2-8f18-1e70c04d3163)
![image](https://github.com/user-attachments/assets/9aad799f-8130-4ca0-ad65-e610d6b6492d)
![image](https://github.com/user-attachments/assets/873da1b3-6602-4262-b62a-fc8b390c86d2)

2024-11-27 19:59 UTC, closed without merging